### ISSUE TITLE
Homebrew-anytap is broken due to upstream change

### ISSUE THREAD

**Issue by xu-cheng** [telemachus/homebrew-anytap#8]
I just merged https://github.com/Homebrew/homebrew/pull/39524 which introduces a new structure to read tap formulae. In short, symlink will not exist instead homebrew reads tap formulae directly from directories.

Unfortunately, this also breaks homebrew-anytap. You need to update this tool to make it work again. In particular `link_tap_formula`, `unlink_tap_formula` are gone.

**Comment by telemachus** [comment]
Thanks for letting me know. I will take a look and get to this ASAP.

**Comment by telemachus** [comment]
Actually @xu-cheng I just checked Homebrew/homebrew#39524, and it's a huge merge (30 commits with 33 files changed). Can you explain briefly what the new structure for taps is (or point me to the relevant files)? Thanks.

**Comment by xu-cheng** [comment]
Homebrew used to read tap formula through symlink. Now it just searches the formula directly inside tap repository folder. So it simplifies things a lot, all you need to do is putting tap files inside `Library/Taps/`.

FYI, https://github.com/Homebrew/homebrew/commit/d3df25a3608c65d25537421ddfaa2060912ecbf7 is the relevant commit.

**Comment by telemachus** [comment]
@xu-cheng Ah, perfect. In that case, the change should be pretty simple. Thanks for the clarification.

**Comment by telemachus** [comment]
@xu-cheng Thanks for the notice and the help here identifying the key changes. I've added you to the contributor list.
